[versions]
agp = "8.9.0"
kotlin = "2.0.21"
core-ktx = "1.15.0"
activity = "1.10.1"
viewmodel = "2.8.7"
material3 = "1.3.1"
material-icons-extended = "1.7.8"
ui-tooling-preview-android = "1.7.8"
libsu = "6.0.0"
documentfile = "1.0.1"
#junit = "4.13.2"
#junitVersion = "1.2.1"
#espressoCore = "3.6.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel" }
preference = { group = "me.zhanghai.compose.preference", name = "library", version = "1.1.1" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "ui-tooling-preview-android" }
libsu = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
