name: Debug CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  download-translation:
    uses: ./crowdin_download.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: ./metadata

      - name: Write sign info
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "apk"
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
